/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/order": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.order.id"];
          user_id?: parameters["rowFilter.order.user_id"];
          date?: parameters["rowFilter.order.date"];
          amount?: parameters["rowFilter.order.amount"];
          status?: parameters["rowFilter.order.status"];
          payment_ref?: parameters["rowFilter.order.payment_ref"];
          cafe_id?: parameters["rowFilter.order.cafe_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["order"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** order */
          order?: definitions["order"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.order.id"];
          user_id?: parameters["rowFilter.order.user_id"];
          date?: parameters["rowFilter.order.date"];
          amount?: parameters["rowFilter.order.amount"];
          status?: parameters["rowFilter.order.status"];
          payment_ref?: parameters["rowFilter.order.payment_ref"];
          cafe_id?: parameters["rowFilter.order.cafe_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.order.id"];
          user_id?: parameters["rowFilter.order.user_id"];
          date?: parameters["rowFilter.order.date"];
          amount?: parameters["rowFilter.order.amount"];
          status?: parameters["rowFilter.order.status"];
          payment_ref?: parameters["rowFilter.order.payment_ref"];
          cafe_id?: parameters["rowFilter.order.cafe_id"];
        };
        body: {
          /** order */
          order?: definitions["order"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/cart": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cart.id"];
          user_id?: parameters["rowFilter.cart.user_id"];
          totalAmount?: parameters["rowFilter.cart.totalAmount"];
          cafe_id?: parameters["rowFilter.cart.cafe_id"];
          createdAt?: parameters["rowFilter.cart.createdAt"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["cart"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** cart */
          cart?: definitions["cart"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cart.id"];
          user_id?: parameters["rowFilter.cart.user_id"];
          totalAmount?: parameters["rowFilter.cart.totalAmount"];
          cafe_id?: parameters["rowFilter.cart.cafe_id"];
          createdAt?: parameters["rowFilter.cart.createdAt"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cart.id"];
          user_id?: parameters["rowFilter.cart.user_id"];
          totalAmount?: parameters["rowFilter.cart.totalAmount"];
          cafe_id?: parameters["rowFilter.cart.cafe_id"];
          createdAt?: parameters["rowFilter.cart.createdAt"];
        };
        body: {
          /** cart */
          cart?: definitions["cart"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/cart_item": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cart_item.id"];
          cart_id?: parameters["rowFilter.cart_item.cart_id"];
          total_price?: parameters["rowFilter.cart_item.total_price"];
          qty?: parameters["rowFilter.cart_item.qty"];
          menu_id?: parameters["rowFilter.cart_item.menu_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["cart_item"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** cart_item */
          cart_item?: definitions["cart_item"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cart_item.id"];
          cart_id?: parameters["rowFilter.cart_item.cart_id"];
          total_price?: parameters["rowFilter.cart_item.total_price"];
          qty?: parameters["rowFilter.cart_item.qty"];
          menu_id?: parameters["rowFilter.cart_item.menu_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cart_item.id"];
          cart_id?: parameters["rowFilter.cart_item.cart_id"];
          total_price?: parameters["rowFilter.cart_item.total_price"];
          qty?: parameters["rowFilter.cart_item.qty"];
          menu_id?: parameters["rowFilter.cart_item.menu_id"];
        };
        body: {
          /** cart_item */
          cart_item?: definitions["cart_item"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/user": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          updated_at?: parameters["rowFilter.user.updated_at"];
          username?: parameters["rowFilter.user.username"];
          avatar_url?: parameters["rowFilter.user.avatar_url"];
          firstname?: parameters["rowFilter.user.firstname"];
          lastname?: parameters["rowFilter.user.lastname"];
          cafe_owner?: parameters["rowFilter.user.cafe_owner"];
          address?: parameters["rowFilter.user.address"];
          phone?: parameters["rowFilter.user.phone"];
          gender?: parameters["rowFilter.user.gender"];
          email?: parameters["rowFilter.user.email"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["user"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** user */
          user?: definitions["user"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          updated_at?: parameters["rowFilter.user.updated_at"];
          username?: parameters["rowFilter.user.username"];
          avatar_url?: parameters["rowFilter.user.avatar_url"];
          firstname?: parameters["rowFilter.user.firstname"];
          lastname?: parameters["rowFilter.user.lastname"];
          cafe_owner?: parameters["rowFilter.user.cafe_owner"];
          address?: parameters["rowFilter.user.address"];
          phone?: parameters["rowFilter.user.phone"];
          gender?: parameters["rowFilter.user.gender"];
          email?: parameters["rowFilter.user.email"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.user.id"];
          updated_at?: parameters["rowFilter.user.updated_at"];
          username?: parameters["rowFilter.user.username"];
          avatar_url?: parameters["rowFilter.user.avatar_url"];
          firstname?: parameters["rowFilter.user.firstname"];
          lastname?: parameters["rowFilter.user.lastname"];
          cafe_owner?: parameters["rowFilter.user.cafe_owner"];
          address?: parameters["rowFilter.user.address"];
          phone?: parameters["rowFilter.user.phone"];
          gender?: parameters["rowFilter.user.gender"];
          email?: parameters["rowFilter.user.email"];
        };
        body: {
          /** user */
          user?: definitions["user"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/review": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.review.id"];
          user_id?: parameters["rowFilter.review.user_id"];
          cafe_id?: parameters["rowFilter.review.cafe_id"];
          content?: parameters["rowFilter.review.content"];
          rating?: parameters["rowFilter.review.rating"];
          date?: parameters["rowFilter.review.date"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["review"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** review */
          review?: definitions["review"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.review.id"];
          user_id?: parameters["rowFilter.review.user_id"];
          cafe_id?: parameters["rowFilter.review.cafe_id"];
          content?: parameters["rowFilter.review.content"];
          rating?: parameters["rowFilter.review.rating"];
          date?: parameters["rowFilter.review.date"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.review.id"];
          user_id?: parameters["rowFilter.review.user_id"];
          cafe_id?: parameters["rowFilter.review.cafe_id"];
          content?: parameters["rowFilter.review.content"];
          rating?: parameters["rowFilter.review.rating"];
          date?: parameters["rowFilter.review.date"];
        };
        body: {
          /** review */
          review?: definitions["review"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/menu": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu.id"];
          name?: parameters["rowFilter.menu.name"];
          description?: parameters["rowFilter.menu.description"];
          price?: parameters["rowFilter.menu.price"];
          image?: parameters["rowFilter.menu.image"];
          available?: parameters["rowFilter.menu.available"];
          cafe_id?: parameters["rowFilter.menu.cafe_id"];
          category_id?: parameters["rowFilter.menu.category_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["menu"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** menu */
          menu?: definitions["menu"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu.id"];
          name?: parameters["rowFilter.menu.name"];
          description?: parameters["rowFilter.menu.description"];
          price?: parameters["rowFilter.menu.price"];
          image?: parameters["rowFilter.menu.image"];
          available?: parameters["rowFilter.menu.available"];
          cafe_id?: parameters["rowFilter.menu.cafe_id"];
          category_id?: parameters["rowFilter.menu.category_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu.id"];
          name?: parameters["rowFilter.menu.name"];
          description?: parameters["rowFilter.menu.description"];
          price?: parameters["rowFilter.menu.price"];
          image?: parameters["rowFilter.menu.image"];
          available?: parameters["rowFilter.menu.available"];
          cafe_id?: parameters["rowFilter.menu.cafe_id"];
          category_id?: parameters["rowFilter.menu.category_id"];
        };
        body: {
          /** menu */
          menu?: definitions["menu"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/menu_option": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_option.id"];
          name?: parameters["rowFilter.menu_option.name"];
          menu_id?: parameters["rowFilter.menu_option.menu_id"];
          multiple?: parameters["rowFilter.menu_option.multiple"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["menu_option"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** menu_option */
          menu_option?: definitions["menu_option"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_option.id"];
          name?: parameters["rowFilter.menu_option.name"];
          menu_id?: parameters["rowFilter.menu_option.menu_id"];
          multiple?: parameters["rowFilter.menu_option.multiple"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_option.id"];
          name?: parameters["rowFilter.menu_option.name"];
          menu_id?: parameters["rowFilter.menu_option.menu_id"];
          multiple?: parameters["rowFilter.menu_option.multiple"];
        };
        body: {
          /** menu_option */
          menu_option?: definitions["menu_option"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/order_item": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.order_item.id"];
          order_id?: parameters["rowFilter.order_item.order_id"];
          total_price?: parameters["rowFilter.order_item.total_price"];
          qty?: parameters["rowFilter.order_item.qty"];
          menu_id?: parameters["rowFilter.order_item.menu_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["order_item"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** order_item */
          order_item?: definitions["order_item"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.order_item.id"];
          order_id?: parameters["rowFilter.order_item.order_id"];
          total_price?: parameters["rowFilter.order_item.total_price"];
          qty?: parameters["rowFilter.order_item.qty"];
          menu_id?: parameters["rowFilter.order_item.menu_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.order_item.id"];
          order_id?: parameters["rowFilter.order_item.order_id"];
          total_price?: parameters["rowFilter.order_item.total_price"];
          qty?: parameters["rowFilter.order_item.qty"];
          menu_id?: parameters["rowFilter.order_item.menu_id"];
        };
        body: {
          /** order_item */
          order_item?: definitions["order_item"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/cafeteria": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cafeteria.id"];
          name?: parameters["rowFilter.cafeteria.name"];
          image?: parameters["rowFilter.cafeteria.image"];
          about?: parameters["rowFilter.cafeteria.about"];
          owned_by?: parameters["rowFilter.cafeteria.owned_by"];
          slug?: parameters["rowFilter.cafeteria.slug"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["cafeteria"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** cafeteria */
          cafeteria?: definitions["cafeteria"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cafeteria.id"];
          name?: parameters["rowFilter.cafeteria.name"];
          image?: parameters["rowFilter.cafeteria.image"];
          about?: parameters["rowFilter.cafeteria.about"];
          owned_by?: parameters["rowFilter.cafeteria.owned_by"];
          slug?: parameters["rowFilter.cafeteria.slug"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.cafeteria.id"];
          name?: parameters["rowFilter.cafeteria.name"];
          image?: parameters["rowFilter.cafeteria.image"];
          about?: parameters["rowFilter.cafeteria.about"];
          owned_by?: parameters["rowFilter.cafeteria.owned_by"];
          slug?: parameters["rowFilter.cafeteria.slug"];
        };
        body: {
          /** cafeteria */
          cafeteria?: definitions["cafeteria"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/menu_option_item": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_option_item.id"];
          name?: parameters["rowFilter.menu_option_item.name"];
          price?: parameters["rowFilter.menu_option_item.price"];
          menu_option_id?: parameters["rowFilter.menu_option_item.menu_option_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["menu_option_item"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** menu_option_item */
          menu_option_item?: definitions["menu_option_item"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_option_item.id"];
          name?: parameters["rowFilter.menu_option_item.name"];
          price?: parameters["rowFilter.menu_option_item.price"];
          menu_option_id?: parameters["rowFilter.menu_option_item.menu_option_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_option_item.id"];
          name?: parameters["rowFilter.menu_option_item.name"];
          price?: parameters["rowFilter.menu_option_item.price"];
          menu_option_id?: parameters["rowFilter.menu_option_item.menu_option_id"];
        };
        body: {
          /** menu_option_item */
          menu_option_item?: definitions["menu_option_item"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/menu_category": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_category.id"];
          cafe_id?: parameters["rowFilter.menu_category.cafe_id"];
          name?: parameters["rowFilter.menu_category.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["menu_category"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** menu_category */
          menu_category?: definitions["menu_category"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_category.id"];
          cafe_id?: parameters["rowFilter.menu_category.cafe_id"];
          name?: parameters["rowFilter.menu_category.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menu_category.id"];
          cafe_id?: parameters["rowFilter.menu_category.cafe_id"];
          name?: parameters["rowFilter.menu_category.name"];
        };
        body: {
          /** menu_category */
          menu_category?: definitions["menu_category"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  order: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `user.id`.<fk table='user' column='id'/>
     */
    user_id: string;
    /**
     * Format: date
     * @default now()
     */
    date: string;
    /** Format: numeric */
    amount: number;
    /**
     * Format: character varying
     * @default processing
     */
    status: string;
    /** Format: character varying */
    payment_ref: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `cafeteria.id`.<fk table='cafeteria' column='id'/>
     */
    cafe_id: number;
  };
  cart: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `user.id`.<fk table='user' column='id'/>
     */
    user_id: string;
    /**
     * Format: numeric
     * @default 0
     */
    totalAmount: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `cafeteria.id`.<fk table='cafeteria' column='id'/>
     */
    cafe_id: number;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    createdAt: string;
  };
  cart_item: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `cart.id`.<fk table='cart' column='id'/>
     */
    cart_id: number;
    /** Format: numeric */
    total_price: number;
    /**
     * Format: integer
     * @default 1
     */
    qty: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `menu.id`.<fk table='menu' column='id'/>
     */
    menu_id: number;
  };
  user: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /** Format: text */
    username: string;
    /** Format: text */
    avatar_url?: string;
    /** Format: character varying */
    firstname?: string;
    /** Format: character varying */
    lastname?: string;
    /**
     * Format: boolean
     * @default false
     */
    cafe_owner?: boolean;
    /** Format: text */
    address?: string;
    /** Format: text */
    phone?: string;
    /** Format: text */
    gender?: string;
    /** Format: character varying */
    email: string;
  };
  review: {
    /** Format: integer */
    id: number;
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `user.id`.<fk table='user' column='id'/>
     */
    user_id: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `cafeteria.id`.<fk table='cafeteria' column='id'/>
     */
    cafe_id: number;
    /** Format: text */
    content: string;
    /** Format: integer */
    rating: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    date: string;
  };
  menu: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name: string;
    /** Format: text */
    description?: string;
    /** Format: numeric */
    price: number;
    /** Format: text */
    image: string;
    /**
     * Format: boolean
     * @default true
     */
    available?: boolean;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `cafeteria.id`.<fk table='cafeteria' column='id'/>
     */
    cafe_id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `menu_category.id`.<fk table='menu_category' column='id'/>
     */
    category_id?: number;
  };
  menu_option: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name?: string;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `menu.id`.<fk table='menu' column='id'/>
     */
    menu_id?: number;
    /** Format: boolean */
    multiple?: boolean;
  };
  order_item: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `order.id`.<fk table='order' column='id'/>
     */
    order_id: number;
    /** Format: numeric */
    total_price: number;
    /** Format: integer */
    qty: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `menu.id`.<fk table='menu' column='id'/>
     */
    menu_id: number;
  };
  cafeteria: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name: string;
    /** Format: character varying */
    image: string;
    /** Format: character varying */
    about?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `user.id`.<fk table='user' column='id'/>
     */
    owned_by?: string;
    /** Format: character varying */
    slug: string;
  };
  menu_option_item: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character */
    name: string;
    /** Format: numeric */
    price: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `menu_option.id`.<fk table='menu_option' column='id'/>
     */
    menu_option_id: number;
  };
  menu_category: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: integer
     * @description Note:
     * This is a Foreign Key to `cafeteria.id`.<fk table='cafeteria' column='id'/>
     */
    cafe_id?: number;
    /** Format: character varying */
    name: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description order */
  "body.order": definitions["order"];
  /** Format: integer */
  "rowFilter.order.id": string;
  /** Format: uuid */
  "rowFilter.order.user_id": string;
  /** Format: date */
  "rowFilter.order.date": string;
  /** Format: numeric */
  "rowFilter.order.amount": string;
  /** Format: character varying */
  "rowFilter.order.status": string;
  /** Format: character varying */
  "rowFilter.order.payment_ref": string;
  /** Format: bigint */
  "rowFilter.order.cafe_id": string;
  /** @description cart */
  "body.cart": definitions["cart"];
  /** Format: integer */
  "rowFilter.cart.id": string;
  /** Format: uuid */
  "rowFilter.cart.user_id": string;
  /** Format: numeric */
  "rowFilter.cart.totalAmount": string;
  /** Format: integer */
  "rowFilter.cart.cafe_id": string;
  /** Format: timestamp without time zone */
  "rowFilter.cart.createdAt": string;
  /** @description cart_item */
  "body.cart_item": definitions["cart_item"];
  /** Format: integer */
  "rowFilter.cart_item.id": string;
  /** Format: integer */
  "rowFilter.cart_item.cart_id": string;
  /** Format: numeric */
  "rowFilter.cart_item.total_price": string;
  /** Format: integer */
  "rowFilter.cart_item.qty": string;
  /** Format: integer */
  "rowFilter.cart_item.menu_id": string;
  /** @description user */
  "body.user": definitions["user"];
  /** Format: uuid */
  "rowFilter.user.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.user.updated_at": string;
  /** Format: text */
  "rowFilter.user.username": string;
  /** Format: text */
  "rowFilter.user.avatar_url": string;
  /** Format: character varying */
  "rowFilter.user.firstname": string;
  /** Format: character varying */
  "rowFilter.user.lastname": string;
  /** Format: boolean */
  "rowFilter.user.cafe_owner": string;
  /** Format: text */
  "rowFilter.user.address": string;
  /** Format: text */
  "rowFilter.user.phone": string;
  /** Format: text */
  "rowFilter.user.gender": string;
  /** Format: character varying */
  "rowFilter.user.email": string;
  /** @description review */
  "body.review": definitions["review"];
  /** Format: integer */
  "rowFilter.review.id": string;
  /** Format: uuid */
  "rowFilter.review.user_id": string;
  /** Format: integer */
  "rowFilter.review.cafe_id": string;
  /** Format: text */
  "rowFilter.review.content": string;
  /** Format: integer */
  "rowFilter.review.rating": string;
  /** Format: timestamp with time zone */
  "rowFilter.review.date": string;
  /** @description menu */
  "body.menu": definitions["menu"];
  /** Format: integer */
  "rowFilter.menu.id": string;
  /** Format: character varying */
  "rowFilter.menu.name": string;
  /** Format: text */
  "rowFilter.menu.description": string;
  /** Format: numeric */
  "rowFilter.menu.price": string;
  /** Format: text */
  "rowFilter.menu.image": string;
  /** Format: boolean */
  "rowFilter.menu.available": string;
  /** Format: integer */
  "rowFilter.menu.cafe_id": string;
  /** Format: integer */
  "rowFilter.menu.category_id": string;
  /** @description menu_option */
  "body.menu_option": definitions["menu_option"];
  /** Format: integer */
  "rowFilter.menu_option.id": string;
  /** Format: character varying */
  "rowFilter.menu_option.name": string;
  /** Format: integer */
  "rowFilter.menu_option.menu_id": string;
  /** Format: boolean */
  "rowFilter.menu_option.multiple": string;
  /** @description order_item */
  "body.order_item": definitions["order_item"];
  /** Format: integer */
  "rowFilter.order_item.id": string;
  /** Format: integer */
  "rowFilter.order_item.order_id": string;
  /** Format: numeric */
  "rowFilter.order_item.total_price": string;
  /** Format: integer */
  "rowFilter.order_item.qty": string;
  /** Format: bigint */
  "rowFilter.order_item.menu_id": string;
  /** @description cafeteria */
  "body.cafeteria": definitions["cafeteria"];
  /** Format: integer */
  "rowFilter.cafeteria.id": string;
  /** Format: character varying */
  "rowFilter.cafeteria.name": string;
  /** Format: character varying */
  "rowFilter.cafeteria.image": string;
  /** Format: character varying */
  "rowFilter.cafeteria.about": string;
  /** Format: uuid */
  "rowFilter.cafeteria.owned_by": string;
  /** Format: character varying */
  "rowFilter.cafeteria.slug": string;
  /** @description menu_option_item */
  "body.menu_option_item": definitions["menu_option_item"];
  /** Format: integer */
  "rowFilter.menu_option_item.id": string;
  /** Format: character */
  "rowFilter.menu_option_item.name": string;
  /** Format: numeric */
  "rowFilter.menu_option_item.price": string;
  /** Format: integer */
  "rowFilter.menu_option_item.menu_option_id": string;
  /** @description menu_category */
  "body.menu_category": definitions["menu_category"];
  /** Format: integer */
  "rowFilter.menu_category.id": string;
  /** Format: integer */
  "rowFilter.menu_category.cafe_id": string;
  /** Format: character varying */
  "rowFilter.menu_category.name": string;
}

export interface operations {}

export interface external {}
